Fixing compilation errors and minor issues ftc_autonomous.java: * method duplicated within method looks like copy/paste * moved servo related variables inside runOpMode(), and left/right in their respective method they do not need to be at instance level since they are only used within their methods
gamepad.java
* compilation error: class name must match the filename